msp: fix vdec driver build error seen with Android toolchain
It adds missing initializtion for stBuf.hVdec and stBuf.hHandle to fix
the following build error seen with Android toolchain.

drivers/hisilicon/msp/vdec/vdec_v2.0/drv_vdec_intf_k.c: In function 'HI_DRV_VDEC_ChanBufferInit':
drivers/hisilicon/msp/vdec/vdec_v2.0/drv_vdec_intf_k.c:3350:12: error: 'stBuf.hVdec' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     s32Ret = BUFMNG_Create(pstBuf->hVdec, &stBufInstCfg);
            ^
drivers/hisilicon/msp/vdec/vdec_v2.0/drv_vdec_intf_k.c:16231:30: note: 'stBuf.hVdec' was declared here
     HI_DRV_VDEC_STREAM_BUF_S stBuf;
                              ^
drivers/hisilicon/msp/vdec/vdec_v2.0/drv_vdec_intf_k.c:16225:5: error: 'stBuf.hHandle' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     VDEC_Chan_AttachStrmBuf(hVdec, pstBuf->u32Size, HI_INVALID_HANDLE, pstBuf->hHandle);
     ^
drivers/hisilicon/msp/vdec/vdec_v2.0/drv_vdec_intf_k.c:16231:30: note: 'stBuf.hHandle' was declared here
     HI_DRV_VDEC_STREAM_BUF_S stBuf;
                              ^
cc1: all warnings being treated as errors
make[5]: *** [drivers/hisilicon/msp/vdec/vdec_v2.0/drv_vdec_intf_k.o] Error 1

Signed-off-by: Shawn Guo <shawn.guo@linaro.org>